# Generated by Django 4.1.3 on 2023-01-13 13:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_rename_car_cars'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cars',
            options={'ordering': ['name_car'], 'verbose_name': 'Машины в наличии', 'verbose_name_plural': 'Машины в наличии'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['car'], 'verbose_name': 'Клиенты', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterField(
            model_name='cars',
            name='name_car',
            field=models.CharField(max_length=50, verbose_name='Машина'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='year',
            field=models.CharField(max_length=4, verbose_name='Год'),
        ),
        migrations.AlterField(
            model_name='client',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.cars', verbose_name='Машина'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')], verbose_name='Номер телефона'),
        ),
    ]
